=== DonjetaMulaj/mgt/mgt/target/classes/schema-action-rules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.asseco-see.com.tr/schema-action-rules" xmlns:tns="http://www.asseco-see.com.tr/schema-action-rules"
	elementFormDefault="qualified">
	<xs:element name="actions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="action" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="params">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="name" use="required" />
														<xs:attribute name="required" use="required">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="required" />
																	<xs:enumeration value="optional" />
																	<xs:enumeration value="conditional" />
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute type="xs:integer" name="maxLength" use="required" />
														<xs:attribute name="type" use="required">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="string" />
																	<xs:enumeration value="decimal" />
																	<xs:enumeration value="boolean" />
																	<xs:enumeration value="date" />
																	<xs:enumeration value="enum" />
																	<xs:enumeration value="integer"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
														<xs:attribute name="format" use="optional">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:enumeration value="dd-MM-yyyy" />
																	<xs:enumeration value="dd-MM-yyyy HH:mm" />
																	<xs:enumeration value="MM.YYYY" />
																	<xs:enumeration value="[{itemcode, itemname, itemdescription, itemprice, itemquantity}]"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute> 
 														<!-- <xs:attribute type="xs:string" name="ifParamPresent" use="optional" /> -->
 														<xs:attribute type="xs:string" name="ifParamNotPresent" use="optional" />
 														<xs:attribute type="xs:string" name="defaultValue" use="optional" />
 														<xs:attribute type="xs:string" name="enumClass" use="optional" /> 
 														<!-- Write as {param}={value1|value2|...} -->
 														<xs:attribute name="ifParamValue" use="optional">
 															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:pattern value="(\w)+=(([a-zA-Z0-9_])+(\|)?)+"/>
																</xs:restriction>
															</xs:simpleType>
 														</xs:attribute> 
 														<!--  <xs:attribute type="xs:string" name="regex" use="optional" />  -->
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="name" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== DonjetaMulaj/mgt/mgt/target/classes/api-request-param-definitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="http://www.asseco-see.com.tr/schema-action-rules"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.asseco-see.com.tr/schema-action-rules xsd/schema-action-rules.xsd">
	<!-- Parameter definitions for API Actions. Order of parameters should be:
		required, conditional, optional. Make sure you XML validate this file before
		committing any changes -->

	<action name="api-request-param-definitions.xml">
		<params>
			<param name="ACTION" required="required" type="enum" enumClass="goprime.fictive.api.enums.ApiAction" maxLength="128" />
			<param name="EMAIL" required="conditional" type="string" maxLength="64" ifParamNotPresent="USERNAME"/>
			<param name="USERNAME" required="required" type="string"  maxLength="64" ifParamNotPresent="EMAIL"/>
			<param name="PASSWORD" required="required"  type="string" maxLength="64" />
		</params>
	</action>
	<action name="APIADDPROJECT">
		<param name="ACTION" required="required" type="enum" enumClass="goprime.fictive.api.enums.ApiAction" maxLength="128" />
		<param name="EMAIL" required="conditional" type="string" maxLength="64" ifParamNotPresent="USERNAME"/>
		<param name="USERNAME" required="required" type="string"  maxLength="64" ifParamNotPresent="EMAIL"/>
		<param name="PASSWORD" required="required"  type="string" maxLength="64" />
		<param name="PROJECTTYPE" required="required"  type="enum" enumClass="goprime.fictive.domain.enums.ProjectType"  maxLength="64" />
		<param name="CUSTOMERSATISFACTION" required="conditional" type="string" maxLength="256" ifParamValue="PROJECTTYPE=MARKETING"/>
		<param name="STOCK" required="conditional" type="enum" enumClass="goprime.fictive.domain.enums.Stock" maxLength="256" ifParamValue="PROJECTTYPE=MARKETING"/>
		<param name="SALES" required="conditional" type="string" maxLength="1024" ifParamValue="PROJECTTYPE=MARKETING"/>
		<param name="PROMOTIONS" required="conditional"  type="enum" enumClass="goprime.fictive.domain.enums.ProjectType" ifParamValue="PROJECTTYPE=RETAIL" maxLength="64" />	
	</action>
	
	<action name="APIADDPROJECTDATA">
		<param name="ACTION" required="required" type="enum" enumClass="goprime.fictive.api.enums.ApiAction" maxLength="128" />
		<param name="EMAIL" required="conditional" type="string" maxLength="64" ifParamNotPresent="USERNAME"/>
		<param name="USERNAME" required="required" type="string"  maxLength="64" ifParamNotPresent="EMAIL"/>
		<param name="PASSWORD" required="required"  type="string" maxLength="64" />
		<param name="PROJECTID" required="required" type="string" maxLength="64" />
		<param name="TASK" required="optional" type="string" maxLength="1024"/>
		<param name="NOTES" required="optional" type="string" maxLength="1024"/>
	</action>
	
	</actions>

=== DonjetaMulaj/mgt/mgt/resource/api-request-param-definitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="http://www.asseco-see.com.tr/schema-action-rules"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.asseco-see.com.tr/schema-action-rules xsd/schema-action-rules.xsd">
	<!-- Parameter definitions for API Actions. Order of parameters should be:
		required, conditional, optional. Make sure you XML validate this file before
		committing any changes -->

	<action name="api-request-param-definitions.xml">
		<params>
			<param name="ACTION" required="required" type="enum" enumClass="goprime.fictive.api.enums.ApiAction" maxLength="128" />
			<param name="EMAIL" required="conditional" type="string" maxLength="64" ifParamNotPresent="USERNAME"/>
			<param name="USERNAME" required="required" type="string"  maxLength="64" ifParamNotPresent="EMAIL"/>
			<param name="PASSWORD" required="required"  type="string" maxLength="64" />
		</params>
	</action>
	<action name="APIQUERYPROJECT">
		<param name="ACTION" required="required" type="enum" enumClass="goprime.fictive.api.enums.ApiAction" maxLength="128" />
		<param name="EMAIL" required="conditional" type="string" maxLength="64" ifParamNotPresent="USERNAME"/>
		<param name="USERNAME" required="required" type="string"  maxLength="64" ifParamNotPresent="EMAIL"/>
		<param name="PASSWORD" required="required"  type="string" maxLength="64" />
	</action>	
	</actions>
